services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BD_HOST: db
      BD_PORT: 5432
      BD_USER: user
      BD_PASSWORD: 12345
      BD_NAME: carzone
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 4318
    depends_on:
      - db

  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: carzone
    ports:
      - "5432:5432"
    volumes:
      - postgress-data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "4318:4318"
      - "14268:14268"
      - "16686:16686"

volumes:
  postgress-data: