services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      BD_HOST: db
      BD_PORT: 5432
      BD_USER: user
      BD_PASSWORD: 12345
      BD_NAME: carzone
    depends_on:
      - db

  db:
    build:
      context: db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: carzone
    ports:
      - "5432:5432"
    volumes:
      - postgress-data:/var/lib/postgresql/data

volumes:
  postgress-data: